export const photos = {
  rubirosa:
    "https://images.getbento.com/accounts/6f2d27238b2ce91fc78e37fe1866785c/media/images/59002EA__9514.jpg?auto=compress%2Cformat&fit=crop&w=1200",
  thai: "https://static.wixstatic.com/media/c9caa2_c1231262de3e4e6e99138cc07fb6197f~mv2.png/v1/fill/w_980%2Ch_778%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_auto/c9caa2_c1231262de3e4e6e99138cc07fb6197f~mv2.png",
  binx: "https://images.squarespace-cdn.com/content/v1/681bc29a7c14f8425ff96859/b443a9df-9204-4090-b1cf-8b4db0ce52f2/Screenshot%2B2025-11-29%2Bat%2B3.42.00%E2%80%AFPM.png?format=750w",
};
// Demonstration catalog, not a representation of current Blackbird participation.
export const sampleVenues = [
  [
    "rubirosa",
    "Rubirosa",
    "Italian",
    "Nolita",
    "235 Mulberry St, New York, NY",
    2,
    40.7227,
    -73.9962,
    photos.rubirosa,
    "https://www.rubirosanyc.com/",
    "A pizza night that turns into a whole evening.",
    ["Date night", "Good for groups"],
  ],
  [
    "thai-diner",
    "Thai Diner",
    "Thai",
    "Nolita",
    "186 Mott St, New York, NY",
    2,
    40.7208,
    -73.9958,
    photos.thai,
    "https://www.thaidiner.com/",
    "Your downtown diner detour, with something spicy on the table.",
    ["Casual", "Brunch"],
  ],
  [
    "binx",
    "BINX",
    "New American",
    "West Village",
    "39 Greenwich Ave, New York, NY",
    3,
    40.7354,
    -74.0004,
    photos.binx,
    "https://www.binxnyc.com/",
    "Small plates, a round of drinks, and a table worth lingering at.",
    ["Date night", "Good for groups"],
  ],
  [
    "estela",
    "Estela",
    "New American",
    "Nolita",
    "47 E Houston St, New York, NY",
    4,
    40.7248,
    -73.9955,
    "",
    "https://www.estelanyc.com/",
    "An intimate downtown room for a long, leisurely dinner.",
    ["Date night"],
  ],
  [
    "lilia",
    "Lilia",
    "Italian",
    "Williamsburg",
    "567 Union Ave, Brooklyn, NY",
    3,
    40.7175,
    -73.9522,
    "",
    "https://www.lilianewyork.com/",
    "A Brooklyn stop for pasta lovers.",
    ["Date night", "Good for groups"],
  ],
  [
    "superiority-burger",
    "Superiority Burger",
    "Vegetarian",
    "East Village",
    "119 Avenue A, New York, NY",
    2,
    40.7276,
    -73.9837,
    "",
    "https://www.superiorityburger.com/",
    "A neighborhood favorite to put on your meat-free shortlist.",
    ["Vegetarian", "Casual"],
  ],
  [
    "balthazar",
    "Balthazar",
    "French",
    "SoHo",
    "80 Spring St, New York, NY",
    3,
    40.7227,
    -73.9982,
    "",
    "https://balthazarny.com/",
    "A classic downtown brasserie moment.",
    ["Brunch", "Good for groups"],
  ],
  [
    "win-son",
    "Win Son",
    "Taiwanese",
    "Williamsburg",
    "159 Graham Ave, Brooklyn, NY",
    2,
    40.7069,
    -73.9438,
    "",
    "https://winsonbrooklyn.com/",
    "Make a meal of it with friends in Brooklyn.",
    ["Good for groups", "Casual"],
  ],
  [
    "via-carota",
    "Via Carota",
    "Italian",
    "West Village",
    "51 Grove St, New York, NY",
    3,
    40.7333,
    -74.0036,
    "",
    "https://www.viacarota.com/",
    "A West Village address for your next Italian dinner.",
    ["Date night", "Vegetarian"],
  ],
  [
    "cote",
    "COTE",
    "Korean",
    "Flatiron",
    "16 W 22nd St, New York, NY",
    4,
    40.7412,
    -73.9913,
    "",
    "https://www.cotekoreansteakhouse.com/",
    "Put a celebratory Korean steakhouse dinner on the calendar.",
    ["Special occasion", "Good for groups"],
  ],
  [
    "golden-diner",
    "Golden Diner",
    "Diner",
    "Chinatown",
    "123 Madison St, New York, NY",
    2,
    40.7125,
    -73.9947,
    "",
    "https://www.goldendinerny.com/",
    "An easygoing downtown stop for your brunch list.",
    ["Brunch", "Casual"],
  ],
  [
    "los-tacos",
    "Los Tacos No. 1",
    "Mexican",
    "Chelsea",
    "75 9th Ave, New York, NY",
    1,
    40.742,
    -74.006,
    "",
    "https://www.lostacos1.com/",
    "A quick taco stop while exploring Chelsea.",
    ["Quick bite", "Casual"],
  ],
] as const;
export const samplePeople = [
  [
    "demo-maya",
    "Maya Chen",
    "Always ordering one more dish. Nolita → everywhere.",
    "#e85a3e",
  ],
  [
    "demo-jules",
    "Jules Rivera",
    "Brooklyn tables, downtown detours.",
    "#69815e",
  ],
  [
    "demo-sam",
    "Sam Park",
    "In a committed relationship with noodles.",
    "#677ba1",
  ],
];
export const sampleLists = [
  [
    "downtown-date-night",
    "demo-maya",
    "Downtown, after dark",
    "The little rooms and long dinners I keep coming back to.",
    "public",
    "#ed563d",
    ["rubirosa", "binx", "estela", "via-carota"],
  ],
  [
    "pasta-people",
    "demo-jules",
    "For the pasta people",
    "Bring someone who is happy to share. Order another plate.",
    "public",
    "#f5ce4f",
    ["lilia", "rubirosa", "via-carota"],
  ],
  [
    "weekend-wander",
    "demo-sam",
    "A very good Saturday",
    "No big plans. Just a few very good things to eat.",
    "public",
    "#a8bbce",
    ["thai-diner", "golden-diner", "los-tacos", "superiority-burger"],
  ],
] as const;

export const extraPhotos: Record<string, string> = {
  Lilia:
    "https://images.getbento.com/accounts/7bf67b2820625f9f7c33d7b0403a8cca/media/suS7yQ83TqbuYEHpfn2R_Lilia-0276.jpg?w=1200&fit=max&auto=compress,format&cs=origin",
  Estela:
    "https://estelanyc.com/cdn/shop/files/Lobster_with_woodear_mushrooms_grapes_and_currants_1200x600_crop_center.jpg?v=1659966747",
  "Via Carota":
    "https://images.squarespace-cdn.com/content/v1/609dae90c469194aa5b1f0a9/1620946666207-XJKJ8S3D0OSYPJNIIAJN/7_A_FriedArtichokes_v9-183.jpg",
  Balthazar:
    "https://balthazarny.com/wp-content/uploads/2013/09/01_BALTHAZAR-EATER-SCENES-Daniel-Krieger-1010_CROP1.jpg",
  COTE: "https://cdn.prod.website-files.com/64dc46f3bd5126f2de6e5a04/65739b9b725aeb68ac5c985a_BUTCHERSFEAST-forweb.webp",
  "Los Tacos No. 1":
    "https://images.getbento.com/accounts/510cbf777fe58cdd68961f978be1dd35/media/images/27525002OurFood.jpg?w=1200&fit=max&auto=compress,format&cs=origin",
  "Golden Diner":
    "https://images.squarespace-cdn.com/content/v1/5b7f58991aef1d9ac2faf070/d3492566-523d-4014-be8b-ab349fabfced/GoldenDiner_Photographer_%2BMarcusLloyd_1.jpg",
  "Win Son":
    "https://winsonbrooklyn.com/contentful-assets/1f934fb92b633a7631f144bc552bf808-TPxHdUGQ.jpeg",
};
