// Reviewed research only. Regenerated by scripts/research/build-labels.py.
export const restaurantLabelResearch: Record<
  string,
  {
    name: string;
    website: string;
    checkedAt: string;
    labels: { label: string; url: string }[];
  }
> = {
  "023550ea-0b0e-4bb6-a4a7-9d24274fdf9e": {
    name: "Messy",
    website: "https://www.messy-nyc.com/",
    checkedAt: "2026-09-16T15:15:22.272659+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.messy-nyc.com/",
      },
    ],
  },
  "0330eb6f-23cd-45c6-b931-5fd49bc6f498": {
    name: "Miznon",
    website: "https://www.miznonusa.com/",
    checkedAt: "2026-09-16T15:15:25.700892+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.miznonusa.com/",
      },
    ],
  },
  "033fc20d-97e7-4bc9-b68e-c3cf0bff8b29": {
    name: "The Mary Lane",
    website: "https://www.themarylanenyc.com/",
    checkedAt: "2026-09-16T15:16:28.352503+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.themarylanenyc.com/",
      },
    ],
  },
  "03658d1b-c31d-4da4-9726-6cd91d4aca29": {
    name: "PARK AVE KITCHEN BY DAVID BURKE",
    website: "https://parkavekitchenbydb.com/",
    checkedAt: "2026-09-16T15:15:37.472335+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://parkavekitchenbydb.com/menus/",
      },
    ],
  },
  "03e5d323-5b80-45b1-a149-84ac9fff0f0b": {
    name: "Decades Pizza",
    website: "https://decades.pizza/",
    checkedAt: "2026-09-16T15:14:08.602327+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://decades.pizza/",
      },
    ],
  },
  "03fe7a99-1443-4dd1-a775-38a28f81e200": {
    name: "The Nest",
    website: "https://www.thenest.nyc/",
    checkedAt: "2026-09-16T15:16:28.811692+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.thenest.nyc/",
      },
    ],
  },
  "056cacff-411d-4133-943a-b7c172ba7993": {
    name: "Naks",
    website: "https://www.naks.nyc/",
    checkedAt: "2026-09-16T15:15:29.155771+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.naks.nyc/",
      },
    ],
  },
  "05f2c94e-6fc0-4609-8d0d-8817aa4221a6": {
    name: "Lavender Lake",
    website: "http://www.lavenderlake.com/",
    checkedAt: "2026-09-16T15:14:59.529694+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "http://www.lavenderlake.com/",
      },
      {
        label: "Brunch",
        url: "http://www.lavenderlake.com/",
      },
    ],
  },
  "0828291e-ec2f-4912-98b1-ba2ad01882aa": {
    name: "Sushi Ryusei",
    website: "https://sushiryusei.com/",
    checkedAt: "2026-09-16T15:16:16.104747+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://sushiryusei.com/menu/",
      },
    ],
  },
  "0909a12f-9738-4532-9ba9-1ed642222152": {
    name: "Askili Orchard",
    website: "http://www.askiliorchard.com/",
    checkedAt: "2026-09-16T15:13:25.250006+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://askiliorchard.com/",
      },
    ],
  },
  "0dc8403a-fe4b-49e5-b2c5-05cac3fb314b": {
    name: "Palma",
    website: "https://www.palmanyc.com/",
    checkedAt: "2026-09-16T15:15:38.291328+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.palmanyc.com/menus/",
      },
    ],
  },
  "0e4e39f5-65a4-4ced-8a88-499f0f3f3f31": {
    name: "Down the Hatch",
    website: "https://www.downthehatchnyc.com/",
    checkedAt: "2026-09-16T15:14:11.813274+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.downthehatchnyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.downthehatchnyc.com/menus/",
      },
    ],
  },
  "0fbc060c-9a36-4a45-bfb1-967b2a2b5709": {
    name: "Freemans",
    website: "https://www.freemansrestaurant.com/",
    checkedAt: "2026-09-16T15:14:26.827207+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.freemansrestaurant.com/",
      },
      {
        label: "Brunch",
        url: "https://www.freemansrestaurant.com/",
      },
    ],
  },
  "100df00c-ce1d-4d00-b294-00ee5d25570c": {
    name: "Indian Accent",
    website: "https://www.indianaccent.com/newyork",
    checkedAt: "2026-09-16T15:14:42.618645+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.indianaccent.com/newyork",
      },
    ],
  },
  "11be9802-71c1-4bfc-8acd-f5eee10a7590": {
    name: "Tradesman",
    website: "http://www.tradesmanbar.com/",
    checkedAt: "2026-09-16T15:16:39.932228+00:00",
    labels: [
      {
        label: "Brunch",
        url: "http://tradesmanbar.com/",
      },
    ],
  },
  "12bdbde3-6a29-46d5-9d3c-98f2e095a899": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "14b2389e-3d62-4a42-888d-c67ecc7d2567": {
    name: "Mark's Off Madison",
    website: "https://www.marksoffmadison.com/",
    checkedAt: "2026-09-16T15:15:18.409625+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://marksoffmadison.com/menus/",
      },
    ],
  },
  "14eb7693-ea20-4c53-90b6-705a2cec8753": {
    name: "Le Gratin",
    website: "https://legratinnyc.com/",
    checkedAt: "2026-09-16T15:15:00.786640+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://legratinnyc.com/",
      },
    ],
  },
  "14f4c58e-1523-4b95-bb10-d6a97431e14f": {
    name: "Peaches Grand",
    website: "https://www.bcrestaurantgroup.com/location/peaches-grand/",
    checkedAt: "2026-09-16T15:15:41.690563+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.bcrestaurantgroup.com/location/peaches-grand/",
      },
    ],
  },
  "153a319b-df4f-4eef-b9e2-e4d8e8810fa6": {
    name: "Malka - Dumbo",
    website: "https://www.malka-usa.com/dumbo",
    checkedAt: "2026-09-16T15:15:15.194995+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.malka-usa.com/about",
      },
    ],
  },
  "1a68a673-2bff-4027-82d3-004116ce056c": {
    name: "Shmoné",
    website: "https://www.shmonenyc.com/",
    checkedAt: "2026-09-16T15:16:04.680239+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.shmonenyc.com/",
      },
    ],
  },
  "1b869e04-f811-4f37-a1d4-1f0b78d1a1ff": {
    name: "Chez Oskar",
    website: "http://www.chezoskar.com/",
    checkedAt: "2026-09-16T15:13:56.828807+00:00",
    labels: [
      {
        label: "Brunch",
        url: "http://chezoskar.com/menu-1",
      },
    ],
  },
  "1d33922d-bbf7-4a36-8ce0-6db122c6058c": {
    name: "Hellbender",
    website: "https://www.hellbendernyc.com/",
    checkedAt: "2026-09-16T15:14:38.261002+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.hellbendernyc.com/menu",
      },
    ],
  },
  "1d8b2906-30c7-4963-a352-e4fe408bca54": {
    name: "Nuyores",
    website: "https://nuyores.com/",
    checkedAt: "2026-09-16T15:15:32.364511+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.nuyores.com/",
      },
    ],
  },
  "206216af-0779-4f30-b0d2-bfec8fc12c0c": {
    name: "Alta Calidad",
    website: "http://www.altacalidadbk.com/",
    checkedAt: "2026-09-16T15:13:18.453439+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://altacalidadbk.com/",
      },
    ],
  },
  "20a1e50e-b73f-477f-a9ed-ee7ce7557ec1": {
    name: "BETTY",
    website: "http://bettynewyork.com/",
    checkedAt: "2026-09-16T15:13:26.718344+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://bettynewyork.com/",
      },
      {
        label: "Brunch",
        url: "https://bettynewyork.com/menus.html",
      },
    ],
  },
  "25556b42-3032-4a1d-8424-ff69b94f570c": {
    name: "Falansai",
    website: "http://falansai.com/",
    checkedAt: "2026-09-16T15:14:19.817706+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.falansai.com/",
      },
      {
        label: "Vegetarian",
        url: "https://www.falansai.com/menu",
      },
    ],
  },
  "2875050e-5881-4c31-84d7-c16794cea7d5": {
    name: "Cafe Colette",
    website: "https://www.cafe-colette.com/",
    checkedAt: "2026-09-16T15:13:46.519480+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.cafe-colette.com/",
      },
    ],
  },
  "287c1c41-a430-48af-827b-220657d68641": {
    name: "Butcher's Daughter",
    website: "https://thebutchersdaughter.com/",
    checkedAt: "2026-09-16T15:13:44.414726+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://thebutchersdaughter.com/",
      },
    ],
  },
  "29c49b28-c5f2-40ef-90c4-53c8d265bcc0": {
    name: "Bonnie's",
    website: "https://www.bonniesbrooklyn.com/",
    checkedAt: "2026-09-16T15:13:40.895295+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.bonniesbrooklyn.com/menu",
      },
      {
        label: "Brunch",
        url: "https://www.bonniesbrooklyn.com/menu",
      },
    ],
  },
  "2cb41bca-9596-4373-b637-464d9d199e81": {
    name: "Landmark Cevicheria",
    website: "https://www.landmarkcevicheria.com/",
    checkedAt: "2026-09-16T15:14:58.658775+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://landmarkcevicheria.com/about",
      },
      {
        label: "Vegetarian",
        url: "https://landmarkcevicheria.com/about",
      },
    ],
  },
  "2cc0abed-3c7a-44df-b845-af0ab8dd0c2a": {
    name: "Golden Diner",
    website: "http://www.goldendinerny.com/",
    checkedAt: "2026-09-16T15:14:31.475703+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.goldendinerny.com/",
      },
    ],
  },
  "2db942d2-046b-4130-bedf-140f14a1f184": {
    name: "Sereneco",
    website: "https://sereneconyc.com",
    checkedAt: "2026-09-16T15:16:02.682632+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.sereneconyc.com/menus/",
      },
    ],
  },
  "2e85c052-57db-4073-a34e-a1b0dfdfd5ee": {
    name: "Monk McGinns",
    website: "https://monkmcginnsnyc.com/",
    checkedAt: "2026-09-16T15:15:26.912419+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://monkmcginnsnyc.com/",
      },
    ],
  },
  "2e87efa2-a947-4b09-9a7f-b1543b83bbf4": {
    name: "Arden",
    website: "http://ardenbk.com/",
    checkedAt: "2026-09-16T15:13:23.911997+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.ardenbk.com/",
      },
    ],
  },
  "2ec39469-731e-491a-a8b9-234cfbe80f2d": {
    name: "Wenwen",
    website: "http://www.wenwenbrooklyn.com/",
    checkedAt: "2026-09-16T15:16:48.912289+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.wenwenbrooklyn.com/menu",
      },
    ],
  },
  "2f3765ef-845b-4cc0-bcd9-c11f74fa0471": {
    name: "Butcher's Daughter",
    website: "https://thebutchersdaughter.com/",
    checkedAt: "2026-09-16T15:13:44.414726+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://thebutchersdaughter.com/",
      },
    ],
  },
  "30bb7153-3d1a-4195-bb96-dd5631af9d94": {
    name: "Mother's Ruin",
    website: "http://www.mothersruinnyc.com/",
    checkedAt: "2026-09-16T15:15:27.411019+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://mothersruinnyc.com/",
      },
    ],
  },
  "31410501-c7d6-4fc1-bb28-100d3ee10f82": {
    name: "Gnocco",
    website: "http://www.gnocco.com/",
    checkedAt: "2026-09-16T15:14:30.976787+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://www.gnocco.com/brunch",
      },
      {
        label: "Brunch",
        url: "https://www.gnocco.com/",
      },
    ],
  },
  "318b485a-505e-48c6-b333-12a784b94721": {
    name: "Lucky Tiger",
    website: "http://www.luckytigernyc.com/",
    checkedAt: "2026-09-16T15:15:12.009362+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.luckytigernyc.com/",
      },
    ],
  },
  "3217e647-d468-4f4c-a909-24352a3a7fed": {
    name: "Dhamaka",
    website: "https://www.dhamaka.nyc/",
    checkedAt: "2026-09-16T15:14:10.619424+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.dhamaka.nyc/",
      },
      {
        label: "Brunch",
        url: "https://www.dhamaka.nyc/",
      },
    ],
  },
  "336c2bd7-405e-49c5-83f1-4b46b0d5e2f0": {
    name: "Panzón",
    website: "https://www.panzonbk.com/",
    checkedAt: "2026-09-16T15:15:38.312865+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.panzonbk.com/menus/",
      },
    ],
  },
  "33878fa6-9551-46b1-9b64-502f8c04d7c6": {
    name: "Peck Slip Social",
    website: "https://www.peckslipsocial.com/",
    checkedAt: "2026-09-16T15:15:43.790576+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://www.peckslipsocial.com/",
      },
    ],
  },
  "33aeb7d7-6521-4088-b240-cdc0a5e48032": {
    name: "The Reading Room",
    website: "https://readingroomnyc.com/",
    checkedAt: "2026-09-16T15:16:31.101012+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://readingroomnyc.com/",
      },
    ],
  },
  "33c07024-33c1-468c-aff1-0c27ad118c57": {
    name: "Crispy Heaven bakery and restaurant",
    website: "http://crispyheavennyc.com/",
    checkedAt: "2026-09-16T15:14:03.952038+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://crispyheavennyc.com/",
      },
    ],
  },
  "33da3a99-69c4-4872-9c3a-024f0d5a9297": {
    name: "Kellogg's Diner",
    website: "https://www.kelloggsdinerbk.com/",
    checkedAt: "2026-09-16T15:14:47.992295+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.kelloggsdinernyc.com/menu",
      },
    ],
  },
  "352d684e-294b-43b4-b265-e323afe4e140": {
    name: "Kings County Brewers Collective",
    website: "https://kcbcbeer.com/",
    checkedAt: "2026-09-16T15:14:49.941366+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://kcbcbeer.com/",
      },
    ],
  },
  "357151ef-b56b-41f4-b98f-758e0edbf836": {
    name: "Da Claudio NYC Ristorante",
    website: "http://www.daclaudionyc.com/",
    checkedAt: "2026-09-16T15:14:05.278040+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.daclaudionyc.com/",
      },
    ],
  },
  "35c48f9b-6180-4b7e-b30e-66e912211c3f": {
    name: "Miznon",
    website: "https://www.miznonusa.com/",
    checkedAt: "2026-09-16T15:15:25.700892+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.miznonusa.com/",
      },
    ],
  },
  "377ed320-39a7-4075-adfd-bdf2c4ecf6fd": {
    name: "Bar Moga",
    website: "https://www.barmoga.com/",
    checkedAt: "2026-09-16T15:13:32.217310+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.barmoga.com/",
      },
    ],
  },
  "37bd9bb9-0c4f-4ea9-b66a-908275ccc551": {
    name: "Leon's",
    website: "https://www.leonsnyc.com/",
    checkedAt: "2026-09-16T15:15:04.041010+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.leonsnyc.com/menus/",
      },
    ],
  },
  "386211e9-e415-4ba6-8665-e3c86bcce4d9": {
    name: "Rolo’s",
    website: "http://www.rolosnyc.com/",
    checkedAt: "2026-09-16T15:15:55.777481+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.rolosnyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.rolosnyc.com/menus/",
      },
    ],
  },
  "38649e09-d08c-4900-8d82-b489303dbd76": {
    name: "Ainslie Bowery",
    website:
      "http://www.ainsliebowery.com/?utm_source=local&utm_medium=organic&utm_campaign=gbp-ainsliebowery",
    checkedAt: "2026-09-16T15:13:15.264410+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.ainsliebowery.com/?utm_source=local&utm_medium=organic&utm_campaign=gbp-ainsliebowery",
      },
      {
        label: "Brunch",
        url: "https://www.ainsliebowery.com/?utm_source=local&utm_medium=organic&utm_campaign=gbp-ainsliebowery",
      },
    ],
  },
  "3995fa1e-b8fe-4729-9ed5-942d0c9f5cbb": {
    name: "Gage & Tollner",
    website: "https://www.gageandtollner.com/",
    checkedAt: "2026-09-16T15:14:29.751130+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.gageandtollner.com/gage-and-tollner-menus/",
      },
      {
        label: "Brunch",
        url: "https://www.gageandtollner.com/gage-and-tollner-menus/",
      },
    ],
  },
  "3c3320d4-5b51-4e29-b9f9-9bfb1419b5e6": {
    name: "Good Behavior",
    website: "https://www.goodbehaviornyc.com/",
    checkedAt: "2026-09-16T15:14:32.335885+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.goodbehaviornyc.com/",
      },
    ],
  },
  "3c658c2c-87d3-4f92-bad0-f4221bd2a305": {
    name: "French Louie",
    website: "http://frenchlouienyc.com/",
    checkedAt: "2026-09-16T15:14:26.835980+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://frenchlouienyc.com/",
      },
      {
        label: "Brunch",
        url: "https://frenchlouienyc.com/menus/",
      },
    ],
  },
  "3e974f88-579f-4411-8249-ab928a0a6aac": {
    name: "Ursula Brooklyn",
    website: "http://www.ursulabk.com/",
    checkedAt: "2026-09-16T15:16:43.940278+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.ursulabk.com/menu/",
      },
    ],
  },
  "40a10cc7-dd75-48e2-9669-8f4f5c412e42": {
    name: "David Burke Tavern",
    website: "https://davidburketavern.com/",
    checkedAt: "2026-09-16T15:14:08.173354+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://davidburketavern.com/menus/",
      },
    ],
  },
  "41f472db-539b-4bdb-8ea1-6e314925c1ec": {
    name: "Manuela",
    website: "https://manuela-nyc.com/",
    checkedAt: "2026-09-16T15:15:17.150030+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://manuela-nyc.com/",
      },
      {
        label: "Brunch",
        url: "https://manuela-nyc.com/menus/",
      },
    ],
  },
  "4369130b-6ac4-47cf-83f4-9d3d9d2cb2b6": {
    name: "Little Egg",
    website: "http://www.eggrestaurant.com/",
    checkedAt: "2026-09-16T15:15:08.444643+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.eggrestaurant.com/",
      },
    ],
  },
  "4793d0f4-b0a4-47d9-aabb-9c046e2c4a42": {
    name: "Mr. Melo",
    website: "http://mrmelobar.com/",
    checkedAt: "2026-09-16T15:15:27.881695+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.mrmelobar.com/",
      },
    ],
  },
  "49431bbb-a817-46f6-a41e-6541e7f6f9de": {
    name: "Lin & Daughters",
    website: "https://linanddaughters.com/",
    checkedAt: "2026-09-16T15:15:06.984971+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://linanddaughters.com/",
      },
    ],
  },
  "49516049-f0f7-4694-855b-38c131abdb06": {
    name: "Jora",
    website: "http://www.jorany.com/",
    checkedAt: "2026-09-16T15:14:45.570642+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.jorany.com/aboutus",
      },
    ],
  },
  "49c5f65f-edea-48c1-932c-52ddaa9c9394": {
    name: "Cafe Ornithology",
    website: "https://cafeornithology.com/",
    checkedAt: "2026-09-16T15:13:48.993843+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://cafeornithology.com/",
      },
    ],
  },
  "4b98c0f4-5182-48d3-8d50-a2c0a27a2ba9": {
    name: "The Cactus Shop",
    website: "https://www.thecactusshopnyc.com/",
    checkedAt: "2026-09-16T15:16:23.182311+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.thecactusshopnyc.com/menus/",
      },
    ],
  },
  "4d74aef2-f0e4-4ba3-b98b-0699a2b59002": {
    name: "Hutong New York",
    website: "http://www.hutong-nyc.com/",
    checkedAt: "2026-09-16T15:14:40.238213+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.hutong-nyc.com/menus/",
      },
    ],
  },
  "4de3fdd6-b5b6-4458-9066-63053e47c2db": {
    name: "Ops",
    website: "http://www.opsbk.com/",
    checkedAt: "2026-09-16T15:15:34.530024+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.opsbk.com/",
      },
    ],
  },
  "4e28ba2b-c4b2-42bf-8310-2f00157bb939": {
    name: "Maison Pickle",
    website: "http://www.maisonpickle.com/",
    checkedAt: "2026-09-16T15:15:14.133358+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.maisonpickle.com/menus/",
      },
    ],
  },
  "4ee1faf2-689b-4453-b250-3b79fd508e38": {
    name: "Meadowsweet",
    website: "https://meadowsweetnyc.com",
    checkedAt: "2026-09-16T15:15:20.454176+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "http://www.meadowsweetnyc.com",
      },
    ],
  },
  "4eedce40-72ee-4763-b785-b1878ac422c5": {
    name: "Essential by Christophe",
    website: "https://www.essentialbychristophe.com/",
    checkedAt: "2026-09-16T15:14:17.457733+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.essentialbychristophe.com/",
      },
    ],
  },
  "4f054b6e-3e0d-473a-96bb-52e6af0df6d5": {
    name: "Temple Bar",
    website: "https://www.templebar.co/",
    checkedAt: "2026-09-16T15:16:21.369471+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.templebar.co/",
      },
    ],
  },
  "4f2f90ba-9eea-4d97-8be4-a2b3c2ce61e0": {
    name: "Idaho",
    website: "http://www.idahobarnyc.com/",
    checkedAt: "2026-09-16T15:14:40.404931+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.idahobarnyc.com/",
      },
      {
        label: "Casual",
        url: "https://www.idahobarnyc.com/",
      },
    ],
  },
  "527d9975-8a41-4911-a647-1d10a6269900": {
    name: "Malka",
    website: "https://malka.nyc/",
    checkedAt: "2026-09-16T15:15:14.965200+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.malka-usa.com/about",
      },
    ],
  },
  "5317762a-493d-4242-9309-f0f6c74e1ce2": {
    name: "Wabi Nori Hand Roll Bar",
    website: "https://wabinori.com/",
    checkedAt: "2026-09-16T15:16:48.199411+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.wabinori.com/",
      },
    ],
  },
  "558deee1-350a-49c9-8afe-649c31cc2c22": {
    name: "La Piovra",
    website: "https://lapiovranyc.com/",
    checkedAt: "2026-09-16T15:14:56.338005+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://lapiovranyc.com/",
      },
      {
        label: "Good for groups",
        url: "https://lapiovranyc.com/",
      },
      {
        label: "Casual",
        url: "https://lapiovranyc.com/",
      },
      {
        label: "Brunch",
        url: "https://lapiovranyc.com/food-menu",
      },
    ],
  },
  "56902d27-a0e4-4693-bdf0-a504d2380f63": {
    name: "Maloya",
    website: "http://maloyanyc.com/",
    checkedAt: "2026-09-16T15:15:15.464532+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://maloyanyc.com/menu/",
      },
    ],
  },
  "57cf3618-1f75-4a5c-9b2a-13fdb28a9624": {
    name: "Amarena",
    website: "http://amarenanyc.com/",
    checkedAt: "2026-09-16T15:13:20.022512+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.amarenanyc.com/menu",
      },
    ],
  },
  "57feca88-3c1f-43dd-afac-19d8dec4a538": {
    name: "Bar Louise",
    website: "https://barlouisenyc.com/",
    checkedAt: "2026-09-16T15:13:31.135114+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.barlouisenyc.com/about",
      },
    ],
  },
  "5a2e9ce2-667c-4320-8433-4f0e8ee4aea4": {
    name: "Raoul's",
    website: "http://raouls.com/",
    checkedAt: "2026-09-16T15:15:54.418899+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://raouls.com/",
      },
    ],
  },
  "5a7bd4ed-7565-4e45-856b-ed5561a24604": {
    name: "Marseille",
    website: "https://www.marseillenyc.com/",
    checkedAt: "2026-09-16T15:15:19.078783+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.marseillenyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.marseillenyc.com/menus/",
      },
    ],
  },
  "5e6c34a6-3077-442d-9c04-aa4bdff767ea": {
    name: "Chela",
    website: "http://chelaparkslope.com/",
    checkedAt: "2026-09-16T15:13:55.348211+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.chelaparkslope.com/",
      },
      {
        label: "Brunch",
        url: "https://www.chelaparkslope.com/",
      },
    ],
  },
  "609e9543-c9f7-4b70-92c8-2dcc83f96e0a": {
    name: "Pil Pil",
    website: "http://pilpilnyc.com/",
    checkedAt: "2026-09-16T15:15:46.172570+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://pilpilnyc.com/new-york-upper-east-side-pil-pil-about",
      },
      {
        label: "Brunch",
        url: "https://pilpilnyc.com/",
      },
    ],
  },
  "612d7d02-cf1f-45b9-83f7-c5613901ce9b": {
    name: "Fossetta",
    website: "https://fossetta-nyc.com/",
    checkedAt: "2026-09-16T15:14:24.886362+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://fossetta-nyc.com/",
      },
      {
        label: "Brunch",
        url: "https://fossetta-nyc.com/menus",
      },
    ],
  },
  "6342b810-4d6d-49ec-a82d-ab826c805f54": {
    name: "Port Sa'id",
    website: "https://www.portsaidnyc.com/",
    checkedAt: "2026-09-16T15:15:49.309536+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.portsaidnyc.com/about",
      },
    ],
  },
  "6367660d-3f5c-4981-af4a-b36d4c3c63b3": {
    name: "Eckhart Beer Co.",
    website: "http://eckhartbeer.com/",
    checkedAt: "2026-09-16T15:14:14.189965+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://eckhartbeer.com/about/",
      },
      {
        label: "Brunch",
        url: "https://eckhartbeer.com/drinks/",
      },
    ],
  },
  "6480a836-0be5-4710-92da-6405ee0dfe83": {
    name: "Lindens",
    website: "https://lindensnyc.com",
    checkedAt: "2026-09-16T15:15:07.828615+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.lindensnyc.com/menus/",
      },
    ],
  },
  "65796930-e373-4617-ad93-9c8d157c84f9": {
    name: "Pappardella",
    website: "http://www.pappardella.com/",
    checkedAt: "2026-09-16T15:15:38.711997+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.pappardella.com/",
      },
    ],
  },
  "682b2400-a3bd-4c00-a96e-7b67c5f67784": {
    name: "Fred's Dog House",
    website: "https://www.fredsdoghouse.com/",
    checkedAt: "2026-09-16T15:14:26.343623+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.fredsdoghouse.com/",
      },
    ],
  },
  "685b2d5f-8ca4-4c76-865e-c1d651a94b0f": {
    name: "Golden Hof - Korean Bar & Grill",
    website: "https://www.goldenhof.com/",
    checkedAt: "2026-09-16T15:14:32.307965+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.goldenhof.com/",
      },
    ],
  },
  "6a49bfe1-6ad6-4a16-afb8-44c3c99b3719": {
    name: "Le Pistol Bar & Cafe",
    website: "https://www.lepistolbk.com/",
    checkedAt: "2026-09-16T15:15:01.332105+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.lepistolbk.com/menu-1",
      },
    ],
  },
  "6abb8388-81b0-4761-96d7-886a455fe977": {
    name: "Bad Roman",
    website: "https://www.badromannyc.com/",
    checkedAt: "2026-09-16T15:13:27.329100+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.badromanrestaurants.com/menus-new-york-city/",
      },
    ],
  },
  "6ac751b4-da4c-4c45-a607-bb76f519fe0d": {
    name: "Place des Fêtes",
    website: "http://www.pdfnyc.com/",
    checkedAt: "2026-09-16T15:15:47.843926+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.pdfnyc.com/",
      },
    ],
  },
  "6e874620-b2c2-4c1c-a517-4b6e9e354aad": {
    name: "Bee's Knees",
    website: "https://www.beeskneesbk.com/",
    checkedAt: "2026-09-16T15:13:35.251917+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.beeskneesbk.com/menus",
      },
    ],
  },
  "6f7df853-7924-4bb4-9a8c-00852dd6eef4": {
    name: "Gair",
    website: "https://www.gair-dumbo.com/",
    checkedAt: "2026-09-16T15:14:29.875148+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.gair-dumbo.com/",
      },
    ],
  },
  "70086a3e-968f-44e1-8e5c-8fe6d34d4464": {
    name: "gertrude’s",
    website: "http://www.gertrudes.nyc/",
    checkedAt: "2026-09-16T15:16:54.741701+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.gertrudes.nyc/",
      },
    ],
  },
  "710cc82d-2457-4c88-91b6-3cd68080c6ba": {
    name: "Emblem",
    website: "https://www.emblembk.com/",
    checkedAt: "2026-09-16T15:14:16.693539+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://emblembk.com/about",
      },
      {
        label: "Vegetarian",
        url: "https://emblembk.com/",
      },
      {
        label: "Brunch",
        url: "https://emblembk.com/food-menu?source=header&spot_id=741430&destination=food_menu&promotion=cheeseburger_day",
      },
    ],
  },
  "71412193-d13c-48e8-a847-36fd2a902e24": {
    name: "Midnights",
    website: "https://www.midnightsbk.com/",
    checkedAt: "2026-09-16T15:15:23.053301+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.midnightsbk.com/",
      },
    ],
  },
  "7173d7a8-3826-4ae3-aa2c-1ad117e9065a": {
    name: "Masalawala & Sons",
    website: "http://www.masalawala.com/",
    checkedAt: "2026-09-16T15:15:20.050524+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.masalawala.com/",
      },
    ],
  },
  "7a95e938-101b-4d41-ad0c-9e70d157076b": {
    name: "Foolproof Whiskey Bar",
    website: "https://foolproofbk.com/",
    checkedAt: "2026-09-16T15:14:23.573381+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.foolproofbk.com/",
      },
      {
        label: "Brunch",
        url: "https://www.foolproofbk.com/menu",
      },
    ],
  },
  "7bf48ce6-f190-43d9-adcb-6b86257a5064": {
    name: "Sobre Masa",
    website: "https://sobremasa.com/",
    checkedAt: "2026-09-16T15:16:06.587849+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://sobremasa.com/",
      },
      {
        label: "Brunch",
        url: "https://sobremasa.com/",
      },
    ],
  },
  "822a4442-48f8-44dc-aed2-f0716c66b196": {
    name: "Emily Brooklyn",
    website: "https://www.pizzalovesemily.com/",
    checkedAt: "2026-09-16T15:14:16.695897+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.pizzalovesemily.com/menus-brooklyn/",
      },
    ],
  },
  "8396f358-f710-43c1-8c2b-9095ac48fb27": {
    name: "AURA Tapas & Cocktail Bar",
    website: "http://www.aurabarandkitchen.com/",
    checkedAt: "2026-09-16T15:13:13.432677+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.aurabarandkitchen.com/",
      },
    ],
  },
  "8581261a-6f7f-4b6a-bda9-9f6160df4e34": {
    name: "Malvan",
    website: "https://malvannyc.com/",
    checkedAt: "2026-09-16T15:15:15.971834+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://malvannyc.com/menus/",
      },
    ],
  },
  "85ec983e-b88c-4e5d-9fb9-9f1eb8c75b77": {
    name: "APERITIVO by CARTA",
    website: "http://aperitivobycarta.com/",
    checkedAt: "2026-09-16T15:13:13.332351+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://aperitivobycarta.com/",
      },
    ],
  },
  "865a442f-e845-4d94-9f31-33b50eac657c": {
    name: "K'Far",
    website: "https://kfarbrooklyn.com",
    checkedAt: "2026-09-16T15:14:46.499301+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://kfarbrooklyn.com",
      },
    ],
  },
  "86fc3efc-3e92-48cb-947a-b94fffb64315": {
    name: "Laliko",
    website: "https://laliko.com/",
    checkedAt: "2026-09-16T15:14:58.636138+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://laliko.com/",
      },
    ],
  },
  "88d89fa8-3205-4aaa-805d-a707893160f7": {
    name: "Levantine",
    website: "https://www.levantinenyc.com/",
    checkedAt: "2026-09-16T15:15:05.187683+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.levantinenyc.com/menus",
      },
    ],
  },
  "89456948-1f00-40aa-bb31-5f81a6b81b02": {
    name: "Ferdi",
    website: "https://ferdinyc.com/",
    checkedAt: "2026-09-16T15:14:20.648380+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://ferdinyc.com/new-york-manhatttan-ferdi-ristorante-food-menu",
      },
    ],
  },
  "8b73d6cf-f55b-4aeb-ab55-45515d0cf5cd": {
    name: "Hair of the Dog",
    website: "https://www.hairofthedognyc.com/",
    checkedAt: "2026-09-16T15:14:37.583839+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.hairofthedognyc.com/menus/",
      },
    ],
  },
  "8d74bca7-5df9-48a1-a379-b9704f0bbc73": {
    name: "Carlotto",
    website: "https://carlottonewyork.com/",
    checkedAt: "2026-09-16T15:13:50.407118+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://carlottonewyork.com/",
      },
    ],
  },
  "8e4b3524-b733-4b52-bc88-97a361b750d4": {
    name: "Bar Chuzo",
    website: "https://www.barchuzo.com/",
    checkedAt: "2026-09-16T15:13:29.606623+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.barchuzo.com/",
      },
    ],
  },
  "902e4173-b791-4bcf-b3ff-30800585905b": {
    name: "Bati",
    website: "https://www.batikitchen.com/",
    checkedAt: "2026-09-16T15:13:35.214359+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.batikitchen.com/",
      },
      {
        label: "Good for groups",
        url: "https://www.batikitchen.com/",
      },
    ],
  },
  "91f4f255-df7e-43dc-83d7-2d5d0f26fbd7": {
    name: "Layla",
    website: "https://www.laylabarnyc.com/",
    checkedAt: "2026-09-16T15:14:59.780971+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.laylabarnyc.com/menus/",
      },
    ],
  },
  "9375d4e9-56eb-4ef6-8faa-508a73e03608": {
    name: "Fausto",
    website: "http://www.faustobrooklyn.com/",
    checkedAt: "2026-09-16T15:14:20.204579+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.faustobrooklyn.com/menus",
      },
    ],
  },
  "94216395-0542-492b-954e-a76e7ce644ef": {
    name: "Cicchetti",
    website: "https://cicchettibk.com/",
    checkedAt: "2026-09-16T15:13:58.542834+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.cicchettibk.com/food",
      },
    ],
  },
  "956efac1-e72b-4b9b-b978-279c723ca76d": {
    name: "Vinatería",
    website: "https://www.vinaterianyc.com/",
    checkedAt: "2026-09-16T15:16:46.148691+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.vinaterianyc.com/menus",
      },
    ],
  },
  "95ffdb33-39d7-4ff2-bbce-64149cc2b480": {
    name: "R40",
    website: "http://www.r40lic.com/",
    checkedAt: "2026-09-16T15:15:52.482115+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.r40lic.com/",
      },
    ],
  },
  "9701cf31-7f62-4b5d-98d2-b222be199941": {
    name: "HARVEST KITCHEN",
    website: "http://www.harvestkitchennyc.com/",
    checkedAt: "2026-09-16T15:14:34.749340+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.harvestkitchennyc.com/",
      },
    ],
  },
  "98c1c02d-2721-41a4-97d0-2900ccbdb570": {
    name: "The Lonesome Club",
    website: "https://www.thelonesomeclub.com/",
    checkedAt: "2026-09-16T15:16:27.967376+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.thelonesomeclub.com/",
      },
    ],
  },
  "9b353993-eb1d-438f-aaea-50ed234ac060": {
    name: "Hoexters",
    website: "https://www.hoexters.com/",
    checkedAt: "2026-09-16T15:14:39.383069+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.hoexters.com/",
      },
    ],
  },
  "9bc7bbd0-4b22-4fe5-b5ca-c6c7404d0877": {
    name: "Copinette",
    website: "https://copinettenyc.com/",
    checkedAt: "2026-09-16T15:14:01.757321+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://copinettenyc.com/",
      },
    ],
  },
  "9c2538cb-c7a7-4127-9a95-77759b31ca2e": {
    name: "Miznon",
    website: "https://www.miznonusa.com/",
    checkedAt: "2026-09-16T15:15:25.700892+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.miznonusa.com/",
      },
    ],
  },
  "9d8ad6ae-6148-4c24-87ea-cf0d5af25e8d": {
    name: "Cafe Commerce",
    website: "http://cafecommercenyc.com/",
    checkedAt: "2026-09-16T15:13:47.087019+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.cafecommercenyc.com/daily-menu",
      },
    ],
  },
  "9da74f1d-70b8-4b90-8213-b70109ab5f11": {
    name: "Somm Time",
    website: "https://sommtimenyc.com/",
    checkedAt: "2026-09-16T15:16:08.131724+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://sommtimenyc.com/",
      },
    ],
  },
  "a0ef3868-0382-41ca-9062-417050fbe64b": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "a3ed438a-1823-4a42-a2c9-cb312aef34e8": {
    name: "Miznon",
    website: "https://www.miznonusa.com/",
    checkedAt: "2026-09-16T15:15:25.700892+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.miznonusa.com/",
      },
    ],
  },
  "a4cabd8a-b294-4594-98ef-2bea626154eb": {
    name: "Speedy Romeo",
    website: "https://www.speedyromeo.com/",
    checkedAt: "2026-09-16T15:16:10.618850+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.speedyromeo.com/",
      },
      {
        label: "Brunch",
        url: "https://www.speedyromeo.com/menus/",
      },
    ],
  },
  "a4d5180d-72ff-4b90-aea6-f1826e7e7bca": {
    name: "Flex Mussels",
    website: "http://www.flexmussels.com/",
    checkedAt: "2026-09-16T15:14:22.546911+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://flexmussels.com/",
      },
    ],
  },
  "a50e6ce2-a137-4b16-906e-6d1c981ea977": {
    name: "Aita",
    website: "http://www.aitaclintonhill.com/",
    checkedAt: "2026-09-16T15:13:15.597855+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.aitaclintonhill.com/",
      },
    ],
  },
  "a5f5be4f-2189-4221-a178-d421cd0ab975": {
    name: "Nina’s Great Burrito Bar",
    website: "http://ninasgreatburrito.com/",
    checkedAt: "2026-09-16T15:15:29.911917+00:00",
    labels: [
      {
        label: "Brunch",
        url: "http://ninasgreatburritobar.com",
      },
    ],
  },
  "a665cc4d-c60a-48be-bca5-852d097c526f": {
    name: "Amélie UWS",
    website: "https://www.amelieupperwest.com/",
    checkedAt: "2026-09-16T15:13:21.726211+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.ameliewinebar.com/uws/menus/dinner",
      },
    ],
  },
  "a82f782f-9740-4670-a226-d1f80860f3bc": {
    name: "Animo!",
    website: "https://animonyc.com/",
    checkedAt: "2026-09-16T15:13:22.257461+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://animonyc.com/",
      },
    ],
  },
  "a88ccf77-5fc8-4abf-b10b-2a3fe7dfddef": {
    name: "The Purple Tongue Wine Bar",
    website: "https://www.thepurpletonguenyc.com/",
    checkedAt: "2026-09-16T15:16:29.703946+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.thepurpletonguenyc.com/menus",
      },
    ],
  },
  "aa4bd176-9589-4b76-a22c-d7f0f77542ae": {
    name: "Little Honey",
    website: "http://littlehoneybk.com/",
    checkedAt: "2026-09-16T15:15:09.179849+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.littlehoneybk.com/",
      },
    ],
  },
  "ac76e560-c4fc-4f1b-bcb6-47dfb56f3795": {
    name: "Miznon",
    website: "https://www.miznonusa.com/",
    checkedAt: "2026-09-16T15:15:25.700892+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.miznonusa.com/",
      },
    ],
  },
  "accc3717-2b90-46f2-90d8-7bf75f714861": {
    name: "Due West",
    website: "https://www.duewestnyc.com/",
    checkedAt: "2026-09-16T15:14:13.622393+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.duewestnyc.com/menus/",
      },
    ],
  },
  "adea3f01-7a91-494a-b0be-f7c067eeae1f": {
    name: "Peaches Lewis",
    website: "https://www.bcrestaurantgroup.com/location/peaches-kitchen-bar/",
    checkedAt: "2026-09-16T15:15:42.834194+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.bcrestaurantgroup.com/location/peaches-kitchen-bar/",
      },
    ],
  },
  "aec582dc-5f47-40c3-ab10-1da436d69e2e": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "af484e3a-b6df-4aed-a4f6-5f684e75a9ec": {
    name: "La Contenta",
    website: "https://lacontentagreenpoint.com/",
    checkedAt: "2026-09-16T15:14:55.375011+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.lacontentagreenpoint.com/",
      },
    ],
  },
  "b030ab13-2d70-4207-a421-c85b1f9468c0": {
    name: "La Goulue New York",
    website: "http://lagouluerestaurant.com/",
    checkedAt: "2026-09-16T15:14:55.616395+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.lagouluerestaurant.com/menus/",
      },
    ],
  },
  "b3b93fae-9422-45d1-923d-628d2c94f0f3": {
    name: "Cafe Mado",
    website: "http://www.cafemadonyc.com/",
    checkedAt: "2026-09-16T15:13:47.916133+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.cafemadonyc.com/",
      },
    ],
  },
  "b4ff6fe2-e06f-468e-bce5-82ef79b8e641": {
    name: "Printers Alley",
    website: "http://www.printersalleynyc.com/",
    checkedAt: "2026-09-16T15:15:50.010552+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.printersalleynyc.com/",
      },
    ],
  },
  "b59c27f4-eadd-486f-bed5-76de15ee66a2": {
    name: "Frijoleros",
    website: "http://frijolerosbk.com/",
    checkedAt: "2026-09-16T15:14:28.385830+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://frijolerosbk.com/",
      },
    ],
  },
  "b85c5ea3-60ba-4b2f-ac0d-4457cb3e85e8": {
    name: "Sunday in Brooklyn",
    website: "https://sundayinbrooklyn.com",
    checkedAt: "2026-09-16T15:16:14.459686+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.sundayinbrooklyn.com/menus/",
      },
    ],
  },
  "b918d599-d84c-409d-9068-8d3499dcb20b": {
    name: "Ops",
    website: "http://www.opsbk.com/",
    checkedAt: "2026-09-16T15:15:34.530024+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.opsbk.com/",
      },
    ],
  },
  "b99a9391-52ea-46c2-8b86-ac91d8b04a7c": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "baf4a3d9-c7c0-4c1f-93b1-b413a4b8bbc6": {
    name: "Le Rivage",
    website: "https://www.lerivagenyc.com/",
    checkedAt: "2026-09-16T15:15:03.034106+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.lerivagenyc.com/",
      },
    ],
  },
  "bba3e394-0526-47e9-b1fe-eb42a12c8b2e": {
    name: "Nick's Pizza",
    website: "http://www.nicksnyc.com/",
    checkedAt: "2026-09-16T15:15:29.733268+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.nicksnyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.nicksnyc.com/",
      },
    ],
  },
  "bd65de9d-d152-4455-ac40-d39da85ae61a": {
    name: "Amali NYC",
    website: "https://www.amalinyc.com/",
    checkedAt: "2026-09-16T15:13:19.913829+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.amalinyc.com/",
      },
    ],
  },
  "bdf6d5a0-fc66-4705-ad70-1d771906fc04": {
    name: "Maison Premiere",
    website: "https://maisonpremiere.com/",
    checkedAt: "2026-09-16T15:15:14.598904+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://maisonpremiere.com/",
      },
    ],
  },
  "bfa59846-baec-4dbf-8a74-d5fd21a8a21a": {
    name: "Trapizzino",
    website: "https://www.trapizzinousa.com/",
    checkedAt: "2026-09-16T15:16:40.053372+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.trapizzinousa.com/menus/",
      },
    ],
  },
  "c08263af-4808-40c6-93aa-f7d10015d846": {
    name: "Orsay",
    website: "http://www.orsayrestaurant.com/",
    checkedAt: "2026-09-16T15:15:35.002118+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.orsayrestaurant.com/menus/",
      },
    ],
  },
  "c3dd21be-c0e0-445e-a1f0-f94615cd526a": {
    name: "Subject: A Cocktail Bar",
    website: "http://subject-les.com/",
    checkedAt: "2026-09-16T15:16:12.836891+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.subject-les.com/",
      },
    ],
  },
  "c54a3b6a-c31b-49b4-8af1-2dfb70ff3eec": {
    name: "Anton's",
    website: "https://www.antonsnyc.com/",
    checkedAt: "2026-09-16T15:13:22.351730+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.antonsnyc.com/menus/",
      },
    ],
  },
  "c6132e34-ae06-40ea-83b5-c899aefc79df": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "c860b984-4a10-4090-9e63-31a24502ecf5": {
    name: "Kurant Wine Bar",
    website: "https://kurantnyc.com/",
    checkedAt: "2026-09-16T15:14:52.789562+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.kurantnyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.kurantnyc.com/",
      },
    ],
  },
  "c877042b-2a0e-4ae2-abff-046b47e5e65c": {
    name: "The Drunken Munkey",
    website: "http://www.drunkenmunkey.com/",
    checkedAt: "2026-09-16T15:16:23.721206+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://drunkenmunkey.com/",
      },
      {
        label: "Good for groups",
        url: "https://drunkenmunkey.com/",
      },
      {
        label: "Vegetarian",
        url: "https://drunkenmunkey.com/",
      },
      {
        label: "Brunch",
        url: "https://drunkenmunkey.com/",
      },
    ],
  },
  "c87b237a-20bb-45ee-9063-1bd9e8a8f0c6": {
    name: "OTB",
    website: "http://www.otbbk.com/",
    checkedAt: "2026-09-16T15:15:32.601920+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "http://www.otbbk.com/",
      },
      {
        label: "Brunch",
        url: "http://www.otbbk.com/",
      },
    ],
  },
  "c8b3017a-5dda-4f69-864c-15aad1f23dea": {
    name: "Leo",
    website: "http://leo-nyc.com/",
    checkedAt: "2026-09-16T15:15:03.581753+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.leo-nyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.leo-nyc.com/",
      },
    ],
  },
  "c8dd0723-0764-400c-9019-349d2d8aed82": {
    name: "Fred's",
    website: "https://www.fredsnyc.com/",
    checkedAt: "2026-09-16T15:14:26.276089+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://fredsnyc.com/",
      },
    ],
  },
  "c98c0b63-e5e2-449c-8963-fb9e66ef08b1": {
    name: "Lilia",
    website: "http://www.lilianewyork.com/",
    checkedAt: "2026-09-16T15:15:06.404886+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.lilianewyork.com/",
      },
    ],
  },
  "cbb0df00-4a96-48a0-96e8-1f7d0b8edc2e": {
    name: "Colonia Verde",
    website: "https://www.coloniaverdenyc.com/",
    checkedAt: "2026-09-16T15:14:00.107705+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.coloniaverdenyc.com/menus",
      },
    ],
  },
  "cd9800c7-1e52-4bed-86dc-00269f788b52": {
    name: "Bar Italia",
    website: "http://www.baritaliamadison.com/",
    checkedAt: "2026-09-16T15:13:30.092100+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.baritaliamadison.com/about/",
      },
    ],
  },
  "ce1dd030-71d5-40f9-acfe-272143a118b9": {
    name: "Titán",
    website: "https://www.titan-nyc.com/",
    checkedAt: "2026-09-16T15:16:37.980289+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.titan-nyc.com/",
      },
    ],
  },
  "cf48a681-4ddf-4044-b525-b101de1e5733": {
    name: "Pineapple Club",
    website: "https://www.pineappleclub.com/",
    checkedAt: "2026-09-16T15:15:46.340549+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.pineappleclub.com/about",
      },
      {
        label: "Brunch",
        url: "https://www.pineappleclub.com/menus",
      },
    ],
  },
  "d0fb29a0-7b0b-4786-aedf-8178e806461c": {
    name: "All Buru",
    website: "http://www.allburu.com/",
    checkedAt: "2026-09-16T15:13:17.655756+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://www.allburu.com/",
      },
    ],
  },
  "d13a204f-3338-4c94-826a-53c44e4d7e73": {
    name: "Leuca",
    website: "http://leuca.com/",
    checkedAt: "2026-09-16T15:15:04.473814+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.leuca.com/menus/",
      },
    ],
  },
  "d1ca1e3c-dbd5-4dde-94a9-eb7d63ea2fc8": {
    name: "Olmo",
    website: "https://olmobk.com/",
    checkedAt: "2026-09-16T15:15:34.300417+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.olmobk.com/",
      },
      {
        label: "Brunch",
        url: "https://www.olmobk.com/menus",
      },
    ],
  },
  "d21b1423-351b-4985-a93b-f77ec265496e": {
    name: "LaRina Pastificio e Vino",
    website: "https://larinabk.com/",
    checkedAt: "2026-09-16T15:14:57.445172+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://larinabrooklyn.com/",
      },
    ],
  },
  "d21d3ea0-d024-49fd-b951-9e38d1d308b9": {
    name: "Debajo",
    website: "https://www.godebajo.com/",
    checkedAt: "2026-09-16T15:14:08.572049+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.godebajo.com/",
      },
      {
        label: "Brunch",
        url: "https://www.godebajo.com/",
      },
    ],
  },
  "d276844b-3703-49f4-ba51-c8cd8292cf0b": {
    name: "Raf's",
    website: "https://www.rafsnewyork.com/",
    checkedAt: "2026-09-16T15:15:53.404980+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.rafsnewyork.com/",
      },
    ],
  },
  "d3ca8a5f-95e9-4348-9643-9c41eaf34cd3": {
    name: "by & by",
    website: "https://byandbynyc.com/",
    checkedAt: "2026-09-16T15:16:54.541142+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://byandbynyc.com/food-menu",
      },
    ],
  },
  "d4971aed-a1cb-4b11-b1aa-59396d8023b5": {
    name: "GERTIE",
    website: "https://www.gertie.nyc/",
    checkedAt: "2026-09-16T15:14:29.232614+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.gertie.nyc/about",
      },
    ],
  },
  "daa8f770-b4b3-40c7-b5f0-3fc1724d9c71": {
    name: "Aldo Sohm Wine Bar",
    website: "http://www.aldosohmwinebar.com/",
    checkedAt: "2026-09-16T15:13:16.034063+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.aldosohmwinebar.com/",
      },
    ],
  },
  "dc5068ab-30f4-40d8-b9e3-b868fcae965d": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "dcb1f7bb-4de3-4ad3-bc70-1e96240e80fa": {
    name: "Randolph Beer",
    website: "https://www.randolphbeer.com/",
    checkedAt: "2026-09-16T15:15:54.000178+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.randolphbeer.com/menus/",
      },
    ],
  },
  "dd977027-7208-42a7-8010-889bee84f98e": {
    name: "EJ's Luncheonette",
    website: "http://www.ejsluncheonette.com/",
    checkedAt: "2026-09-16T15:14:13.710124+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://ejsluncheonette.com/new-york-upper-east-side-ejs-luncheonette-food-menu",
      },
    ],
  },
  "de43b2db-875e-499f-bed2-4f2da93f07be": {
    name: "Tasca NYC",
    website: "http://www.tasca-nyc.com/",
    checkedAt: "2026-09-16T15:16:20.798363+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://www.tasca-nyc.com/about-us/",
      },
      {
        label: "Brunch",
        url: "https://www.tasca-nyc.com/",
      },
    ],
  },
  "deca6a79-1460-42fc-ad6d-0d89a8418086": {
    name: "Salinas Restaurant",
    website: "http://www.salinasnyc.com/",
    checkedAt: "2026-09-16T15:15:58.859509+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://salinasnyc.com/",
      },
      {
        label: "Good for groups",
        url: "https://salinasnyc.com/",
      },
    ],
  },
  "dfadf579-07df-4464-84b6-6b063107fcb4": {
    name: "Judy Z’s Sports Tavern & Kitchen",
    website: "https://www.judyznyc.com/",
    checkedAt: "2026-09-16T15:14:46.273272+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://www.judyznyc.com/menus/",
      },
      {
        label: "Brunch",
        url: "https://www.judyznyc.com/menus/",
      },
    ],
  },
  "e0ab9d45-cfbd-433e-8ecc-da88a56b9942": {
    name: "Mango Bay",
    website: "http://www.themangobay.com/",
    checkedAt: "2026-09-16T15:15:16.793346+00:00",
    labels: [
      {
        label: "Brunch",
        url: "http://www.themangobay.com/",
      },
    ],
  },
  "e30fa4c6-7fae-4a7d-8014-f2913999db6f": {
    name: "The Stand - Comedy Club",
    website: "https://thestandnyc.com/",
    checkedAt: "2026-09-16T15:16:32.609695+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://thestandnyc.com/",
      },
    ],
  },
  "e34edefb-efc5-4496-a588-542c1898f233": {
    name: "Soledad",
    website: "http://www.soledadnyc.com/",
    checkedAt: "2026-09-16T15:16:07.192101+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.soledadnyc.com/",
      },
    ],
  },
  "e386f9d5-f969-4adb-b1d6-aaabd10791e1": {
    name: "Quick Eternity",
    website: "https://www.quicketernity.nyc/",
    checkedAt: "2026-09-16T15:15:51.847500+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.quicketernity.nyc/menu",
      },
    ],
  },
  "e48f14db-475d-4338-a9f5-a21af8ded4ad": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "e7ee67bb-de74-49fe-864f-1bb0bf6000ff": {
    name: "Kings of Kobe - Wagyu Kitchen & Bar",
    website: "https://www.kingsofkobe.com/",
    checkedAt: "2026-09-16T15:14:50.591206+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.kingsofkobe.com/",
      },
      {
        label: "Brunch",
        url: "https://www.kingsofkobe.com/",
      },
    ],
  },
  "e9c6e0d1-2073-4b9f-866f-f61fea07ea8c": {
    name: "Lin & Daughters",
    website: "https://linanddaughters.com/",
    checkedAt: "2026-09-16T15:15:06.984971+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://linanddaughters.com/",
      },
    ],
  },
  "eba2609e-0049-4169-92e4-fc175556e4d9": {
    name: "L'Express",
    website: "https://www.lexpressnyc.com/",
    checkedAt: "2026-09-16T15:14:53.666351+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.lexpressnyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.lexpressnyc.com/menus/",
      },
    ],
  },
  "ef925a44-937b-4e9c-a20f-c6dd7ce6f747": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "f2bab987-6fc0-41eb-a8d3-89a566901d74": {
    name: "Bareburger",
    website: "https://bareburger.com/",
    checkedAt: "2026-09-16T15:13:33.886880+00:00",
    labels: [
      {
        label: "Vegetarian",
        url: "https://bareburger.com/about/",
      },
    ],
  },
  "f4409f1d-612b-4675-acaf-c8b6b75e025d": {
    name: "Cleo Downtown",
    website: "http://cleodowntown.com/",
    checkedAt: "2026-09-16T15:13:59.570907+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.cleodowntown.com/",
      },
    ],
  },
  "f485e76b-d2ac-4a6c-883d-073e770fbae2": {
    name: "Frenchette",
    website: "http://frenchettenyc.com/",
    checkedAt: "2026-09-16T15:14:27.132358+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.frenchettenyc.com/menus/",
      },
    ],
  },
  "f5c1f39f-f7f3-41eb-9206-763f63740f7a": {
    name: "Strange Delight",
    website: "https://www.strangedelight.nyc/",
    checkedAt: "2026-09-16T15:16:12.488511+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.strangedelight.nyc/",
      },
    ],
  },
  "f8680f08-f359-480a-8a83-4eefe924a8ad": {
    name: "Symposium",
    website: "https://www.symposiumnyc.com/",
    checkedAt: "2026-09-16T15:16:17.654434+00:00",
    labels: [
      {
        label: "Date night",
        url: "https://symposiumnyc.com/",
      },
    ],
  },
  "fa62df72-859b-4aa9-abff-20b68b80ab77": {
    name: "Sound + Fury Brewery and Kitchen",
    website: "http://www.soundandfurybrewing.com/",
    checkedAt: "2026-09-16T15:16:09.195223+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.soundandfurybrewing.com/",
      },
    ],
  },
  "fc243682-af76-4605-b2ce-53ba0afa6353": {
    name: "Pasta Night",
    website: "https://pastanightbk.com/",
    checkedAt: "2026-09-16T15:15:40.688872+00:00",
    labels: [
      {
        label: "Casual",
        url: "https://www.pastanightbk.com/",
      },
      {
        label: "Brunch",
        url: "https://www.pastanightbk.com/",
      },
    ],
  },
  "fd76048d-d946-4dc9-bb36-4fa76ab7e702": {
    name: "Singapore Social",
    website: "https://www.sgsocialnyc.com/",
    checkedAt: "2026-09-16T15:16:04.982311+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.sgsocialnyc.com/",
      },
    ],
  },
  "fe770e57-bf71-40db-9b88-6e86bbc7fea1": {
    name: "Casa Thirteen",
    website: "http://www.casathirteen.com/",
    checkedAt: "2026-09-16T15:13:53.309378+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://casathirteen.com/food-menu",
      },
    ],
  },
  "feffcbae-9bd3-4bf3-9877-3a5ba84e9f41": {
    name: "Oxomoco",
    website: "https://www.oxomoconyc.com/",
    checkedAt: "2026-09-16T15:15:37.079132+00:00",
    labels: [
      {
        label: "Good for groups",
        url: "https://www.oxomoconyc.com/",
      },
      {
        label: "Brunch",
        url: "https://www.oxomoconyc.com/menus/",
      },
    ],
  },
  "ff8e9711-45ee-40bd-9751-0562ea27e37c": {
    name: "The Dutch",
    website: "http://www.thedutchnyc.com/",
    checkedAt: "2026-09-16T15:16:24.908264+00:00",
    labels: [
      {
        label: "Brunch",
        url: "https://www.thedutchnyc.com/menus/",
      },
    ],
  },
};
