"""Build reviewed, location-specific labels; never publish scraped page text.
Usage: python3 scripts/research/build-labels.py CATALOG_JSON RESEARCH_DIR
"""
import collections, json, pathlib, re, sys, unicodedata

root = pathlib.Path(__file__).resolve().parents[2]
catalog = json.loads(pathlib.Path(sys.argv[1]).read_text())['venues']
cache = pathlib.Path(sys.argv[2])
approvals = json.loads((root/'scripts/research/approved-labels.json').read_text())

def normalized(text):
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode().lower()
    text = re.sub(r'(\d+)(st|nd|rd|th)\b', r'\1', text)
    for a, b in {'west':'w','east':'e','north':'n','south':'s','street':'st','avenue':'ave','road':'rd','place':'pl','boulevard':'blvd'}.items():
        text = re.sub(r'\b'+a+r'\b', b, text)
    return re.sub(r'[^a-z0-9]', '', text)

output, skipped = {}, []
for approval in approvals:
    research = json.loads((cache/(approval['key']+'.json')).read_text())
    page = next((p for p in research['pages'] if p['url']==approval['url']), None)
    if not page or approval['tag'] not in page['candidates']:
        raise ValueError('Approval has no evidence: '+str(approval))
    for venue in research['venues']:
        if approval['scope'] != 'brand' and venue['name'] != approval['name']:
            continue
        street = normalized(venue['address'].split(',')[0])
        # Name alone cannot distinguish relocated venues or similarly named branches.
        # Brand-wide claims are the only explicitly reviewed exception.
        texts = normalized(' '.join(p['text'] for p in research['pages']))
        if approval['scope'] != 'brand' and (not street or street not in texts):
            skipped.append({'id':venue['id'],'name':venue['name'],'label':approval['tag'],'reason':'street address not corroborated on fetched pages'})
            continue
        entry = output.setdefault(venue['id'], {'name':venue['name'],'website':research['website'],'checkedAt':research['checkedAt'],'labels':[]})
        if not any(x['label']==approval['tag'] for x in entry['labels']):
            entry['labels'].append({'label':approval['tag'],'url':approval['url']})

header = '// Reviewed research only. Regenerated by scripts/research/build-labels.py.\nexport const restaurantLabelResearch: Record<string, { name: string; website: string; checkedAt: string; labels: { label: string; url: string }[] }> = '
(root/'data/restaurant-labels.ts').write_text(header+json.dumps(dict(sorted(output.items())),ensure_ascii=False,indent=2)+';\n')
counts = collections.Counter(l['label'] for v in output.values() for l in v['labels'])
audit = {'catalogLocations':len(catalog),'labeledLocations':len(output),'counts':dict(counts),'skippedApprovals':skipped,'unlabeledLocations':[{'id':v['id'],'name':v['name'],'reason':'no website' if not v['website'] else 'no reviewed label with corroborated location'} for v in catalog if v['id'] not in output]}
(root/'data/restaurant-label-coverage.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:v for k,v in audit.items() if k not in ('skippedApprovals','unlabeledLocations')}))
print('Address checks excluded',len(skipped),'claims; inspect data/restaurant-label-coverage.json')
